const NAME_LOGO: [RegExp, string][] = [
  [/stripe/i, "stripe"],
  [/github/i, "github"],
  [/vercel/i, "vercel"],
  [/sentry/i, "sentry"],
  [/cloudflare/i, "cloudflare"],
  [/clerk/i, "clerk"],
  [/^(aws|amazon web services)/i, "amazonwebservices"],
  [/kubernetes|\bk8s\b/i, "kubernetes"],
  [/chrome devtools/i, "googlechrome"],
  [/supabase/i, "supabase"],
  [/^neon\b/i, "neon"],
  [/postgres/i, "postgresql"],
  [/mongo/i, "mongodb"],
  [/elastic/i, "elasticsearch"],
  [/qdrant/i, "qdrant"],
  [/redis/i, "redis"],
  [/notion/i, "notion"],
  [/postman/i, "postman"],
  [/linear/i, "linear"],
  [/trello/i, "trello"],
  [/revenue[ -]?cat/i, "revenuecat"],
  [/atlassian/i, "atlassian"],
  [/jira/i, "jira"],
  [/asana/i, "asana"],
  [/airtable/i, "airtable"],
  [/todoist/i, "todoist"],
  [/slack/i, "slack"],
  [/twilio/i, "twilio"],
  [/postiz/i, "postiz"],
  [/hugging[ -]?face/i, "huggingface"],
  [/openrouter/i, "openrouter"],
  [/brave/i, "brave"],
  [/perplexity/i, "perplexity"],
  [/figma/i, "figma"],
  [/resend/i, "resend"],
  [/\bn8n\b/i, "n8n"],
  [/^git\b/i, "git"],
  [/apify/i, "apify"],
  [/browserbase/i, "browserbase"],
  [/composio/i, "composio"],
  [/context7/i, "context7"],
  [/dataforseo/i, "dataforseo"],
  [/deepwiki/i, "deepwiki"],
  [/firecrawl/i, "firecrawl"],
  [/langfuse/i, "langfuse"],
  [/linode/i, "linode"],
  [/microsoft/i, "microsoft"],
  [/parallel search/i, "parallel"],
  [/playwright/i, "playwright"],
  [/tavily/i, "tavily"],
  [/\bexa\b/i, "exa"],
  // The reference servers have no brand. Match them only as the leading word,
  // so a "Team memory" or "Showtime" server keeps its transport badge.
  [/^fetch\b/i, "fetch"],
  [/^filesystem\b/i, "filesystem"],
  [/^memory\b/i, "memory"],
  [/^sequential thinking\b/i, "sequentialthinking"],
  [/^time\b/i, "time"],
];

export function serverLogoKey(name: string): string | null {
  return NAME_LOGO.find(([pattern]) => pattern.test(name))?.[1] ?? null;
}
