const NAME_LOGO: [RegExp, string][] = [
  [/stripe/i, "stripe"],
  [/github/i, "github"],
  [/vercel/i, "vercel"],
  [/sentry/i, "sentry"],
  [/cloudflare/i, "cloudflare"],
  [/clerk/i, "clerk"],
  [/^(aws|amazon web services)/i, "amazonwebservices"],
  [/kubernetes|\bk8s\b/i, "kubernetes"],
  [/chrome devtools/i, "googlechrome"],
  [/supabase/i, "supabase"],
  [/^neon\b/i, "neon"],
  [/postgres/i, "postgresql"],
  [/mongo/i, "mongodb"],
  [/elastic/i, "elasticsearch"],
  [/qdrant/i, "qdrant"],
  [/redis/i, "redis"],
  [/notion/i, "notion"],
  [/postman/i, "postman"],
  [/linear/i, "linear"],
  [/atlassian/i, "atlassian"],
  [/jira/i, "jira"],
  [/asana/i, "asana"],
  [/airtable/i, "airtable"],
  [/todoist/i, "todoist"],
  [/slack/i, "slack"],
  [/twilio/i, "twilio"],
  [/postiz/i, "postiz"],
  [/hugging[ -]?face/i, "huggingface"],
  [/openrouter/i, "openrouter"],
  [/brave/i, "brave"],
  [/perplexity/i, "perplexity"],
  [/figma/i, "figma"],
  [/resend/i, "resend"],
  [/\bn8n\b/i, "n8n"],
  [/^git\b/i, "git"],
];

export function serverLogoKey(name: string): string | null {
  return NAME_LOGO.find(([pattern]) => pattern.test(name))?.[1] ?? null;
}
